language: elixir
elixir: 
  - 1.3.4
otp_release:
  - 19
sudo: false
addons:
  postgresql: '9.4' # Use postgres 9.4
before_script:
# Create the test database
- psql -c 'create database peepchat_test;' -U postgres